### ISSUE TITLE
Support 5.x

### ISSUE THREAD

**Issue by beautyfree** [jclemens24/typeorm-fastify-plugin#191]
fastify v5 has been generally available. Looks like we just need to expect 5.x and everything will works great.

**Comment by iducool** [comment]
I am looking for same. @jclemens24  Please consider this request.

**Comment by jclemens24** [comment]
Thank you for your patience!
Support for Fastify v5 is now available as part of the latest v3.0.0 release. I've updated the plugin meta version to 5.x, and everything should work seamlessly with Fastify v5.
Thanks again for your input and support
